pipelines:
  default:
    - step:
        name: Build
        caches:
          - gradle
        script:
          - bash ./gradlew stage
    - step:
        name: Deploy
        script:
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master