pipelines:
  pull-requests:
    '**':
      - step:
          name: Build
          caches:
            - gradle
          script:
            - bash ./gradlew stage
  branches:
    master:
      - step:
          name: Deploy
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master