pipelines:
  default:
    - step:
        caches:
          - gradle
        script:
          - bash ./gradlew stage
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master